name: CI

on:
  push:
    branches:
      - 'master'
      - 'release-'
    tags: '*'
  pull_request:

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1.0'
          - '1'
          - 'nightly'
        os:
          - ubuntu-latest
          - macos-latest
          # - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      - name: "Pkg.instantiate and install cli"
        run: |
          echo "${PWD}/bin" >> $GITHUB_PATH
          julia --project -e 'using Pkg; Pkg.instantiate()'
          julia --project -e 'using jlpkg; jlpkg.install(; command = "jlpkg-ci", destdir = joinpath(pwd(), "bin"))'
      - name: "Run tests (Unix)"
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
        run: jlpkg-ci --project test --coverage
      - name: "Run tests (Windows)"
        if: matrix.os == 'windows-latest'
        run: cmd /c jlpkg-ci --project test --coverage
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
